### ISSUE TITLE
Including Acceptance criteria when printing

### ISSUE THREAD

**Issue by georgihadzhigeorgiev** [MrTarantula/WIPrint#1]
Hi,

Could you allow inclusion of Acceptance criteria when printing

Kind regards,
Georgi

**Comment by MrTarantula** [comment]
I'll put it below the Description, unless you think it would be better somewhere else.

Eventually I plan on adding a settings page in the Admin Settings section that will allow you to fully customize the fields available.

**Comment by georgihadzhigeorgiev** [comment]
That's great! Thank you!

**Comment by MrTarantula** [comment]
Your extension should have automatically updated. If everything looks good, please rate/review the extension on the [Marketplace](https://marketplace.visualstudio.com/items?itemName=mrtarantula.wiprint).

**Comment by georgihadzhigeorgiev** [comment]
Nice work, cheers!

**Comment by MrTarantula** [comment]
I have released a new version of the extension. which includes per-item customization. You can add any and all fields, and change their order. If you have the extension installed, it should update automatically, and may prompt you for new permissions (storing your configuration). Otherwise, you can find it in the [marketplace](https://marketplace.visualstudio.com/items?itemName=mrtarantula.wiprint).
